GET http://127.0.0.1:3000/api/admin/get/admin
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjY0YjNmNzMxNDkzMDg4MTE3MmI5YzYiLCJyb2xlIjoiQ2xpZW50ZSIsImlhdCI6MTcxNzkwNzQyOH0.df1benCYnAQD-dCBxMP7hQwKy8DOaQxuK2ApooOHleM


###
POST http://127.0.0.1:3000/api/user/login
Content-Type: application/json

{
    "email": "benjamin_rc@tesch.edu.mx",
    "password": "123456789A*"
}

###
POST http://127.0.0.1:3000/api/user/cart/items
Content-Type: application/json

{
    "token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjY0YjNmNzMxNDkzMDg4MTE3MmI5YzYiLCJyb2xlIjoiQ2xpZW50ZSIsImlhdCI6MTcxNzkwNzQyOH0.df1benCYnAQD-dCBxMP7hQwKy8DOaQxuK2ApooOHleM"
}


###
POST http://127.0.0.1:3000/api/admin/get/orders
Content-Type: application/json

{
    "token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjY0YjNmNzMxNDkzMDg4MTE3MmI5YzYiLCJyb2xlIjoiQ2xpZW50ZSIsImlhdCI6MTcxNzk5OTA0OX0.jJvk7USrApC5UGMufo8z6zuy6n9H0fk1usZnvN-iEpc"
}










